## here is how to use dctutor to make dclone tests

source(system.file(package = "dctutor", "dclone.R"))
source(system.file(package = "dctutor", "dcglm.R"))
source(system.file(package = "dctutor", "dcpar.R"))

## dclone documentation
library(dclone)
example(bugs.fit)
example(bugs.parfit)
example(clusterSeed)
example(clusterSize)
example(clusterSplitSB)
example(coef.mcmc.list)
example(dc.fit)
example(dc.parfit)
example(dclone)
example(dcoptions)
example(dctable)
example(errlines)
example(jags.fit)
example(jags.parfit)
example(lambdamax.diag)
example(make.symmetric)
example(mcmcapply)
example(nclones)
example(ovenbird)
example(regmod)
example(snowWrapper)
example(update.mcmc.list)
example(write.jags.model)
